let stopsList = [
    "Diagonal Norte",
    "Obelisco",
    "Catedral Metropolitana",
    "Casa Rosada",
    "Museo del Bicentenario",
    "Galería Güemes",
    "Cabildo de Buenos Aires",
    "Avenida de Mayo",
    "Casa Rosada",
    "Museo del Bicentenario",
    "Café Tortoni",
    "Manzana de las Luces",
    "Cabildo de Buenos Aires",
    "Teatro Avenida",
    "Plaza del Congreso",
    "Congreso de la Nación Argentina",
    "Palacio Barolo",
    "Pasaje Rivarola",
    "Hotel Castelar",
    "Monumento a los Dos Congresos",
    "Paseo de la Historieta",
    "Escultura de Mafalda",
    "Puente de la Mujer",
    "Fragata Sarmiento",
    "Basílica de San Francisco",
    "Plaza de Mayo",
    "Usina del Arte",
    "Caminito",
    "Museo Quinquela Martín",
    "Museo del Cine",
    "La Torre del Fantasma",
    "Estadio Boca Juniors",
    "Puerto Madero",
    "Puente de la Mujer",
    "Buque Escuela Corbeta Uruguay",
    "Museo del Humor",
    "Centro Cultural Néstor Kirchner",
    "Experiencias Náuticas",
    "Río de la Plata",
    "Reserva Ecológica",
    "Colección de Arte Amalia Lacroze de Fortabat",
    "Circuitos Gastronómicos Peatonales",
    "Centro Cultural Néstor Kirchner",
    "Galerías Pacífico",
    "Museo Nacional de Bellas Artes",
    "Floralis Genérica",
    "Biblioteca Nacional",
    "Basílica Nuestra Señora del Pilar",
    "Centro Cultural Recoleta",
    "Cementerio de la Recoleta",
    "Teatro Colón",
    "Obelisco",
    "Teatro Colón",
    "Teatro Cervantes",
    "Galerías Pacífico",
    "Plaza San Martín",
    "Planetario",
    "Planetario Galileo Galileo",
    "Museo de Artes Plásticas Sívori",
    "Paseo el Rosedal",
    "Ecoparque Interactivo",
    "Jardín Japonés",
    "Bosques de Palermo",
    "Mezquita Centro Cultural Islámico Rey Fahd",
    "Campo de Polo",
    "Hipódromo Argentino",
    "Rosedal",
    "Planetario Galileo Galilei",
    "San Telmo",
    "Plaza Dorrego",
    "Iglesia San Pedro Telmo",
    "Museo MAMBA",
    "Museo MACBA",
    "Mercado de San Telmo",
    "La Boca - Caminito",
    "Usina del Arte",
    "Museo Quinquela Martín",
    "Teatro de la Ribera",
    "Puente Transbordador",
    "Estadio Boca Juniors",
    "Belgrano - Barrio Chino",
    "Museo Enrique Larreta",
    "Arco Inaugural Barrio Chino",
    "Barrancas de Belgrano",
    "Museo Sarmiento",
    "Iglesia Inmaculada Concepción del Belgrano",
    "Recoleta",
    "Centro Cultural Recoleta",
    "Cementerio de la Recoleta",
    "Basílica Nuestra Señora del Pilar",
    "Museo Nacional de Bellas Artes",
    "Floralis Genérica",
    "El Monumental (Estadio River Plate)",
    "Museo Deportivo River",
    "Jardín de Esculturas",
    "Paseo de las Américas y Converse Skate Plaza",
    "Museo Islas Malvinas e Islas del Atlántico Sur",
    "Centro Cultural de la Memoria Haroldo Conti",
    "Club Hípico Argentino",
    "Costanera Sur",
    "Paseo de la Gloria",
    "Monumento al Tango",
    "Puente de la Mujer",
    "Fragata Sarmiento",
    "Parque Micaela Bastidas",
    "Av 9 de Julio",
    "Peatonal Florida",
    "Teatro Colón",
    "Plaza San Martín",
    "Galerías Pacífico",
    "Museo de Arte Hispanoamericano Isaac Fernández Blanco",
    "Plaza Italia",
    "Museo Evita",
    "Jardín Japonés",
    "Jardín Botánico Carlos Thays",
    "Rosedal",
    "Ecoparque Interactivo",
    "Delta",
    "Tigre"
];


for (var i = 0; i < stopsList.length; i++) {
    let stop = { name: stopsList[i], code: i,  desciprion: `Stop number ${i}`};
    db.stop.insertOne(stop);
}

for (let i = 1; i <= 50000; i++) {
    let route = {
        name: `route${i}`,
        price: Math.floor(Math.random() * (1000 - 100 + 1)) + 100,
        totalKm: parseFloat((Math.random() * (20 - 1) + 1).toFixed(2)),
        stops: []
    };

    let numStops = Math.floor(Math.random() * (5 - 2 + 1)) + 2;
    for (let j = 0; j < numStops; j++) {
        let randomStop = Math.floor(Math.random() * stopsList.length);
        route.stops.push(randomStop);
    }

    db.route.insert(route);
}